repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
    - id: check-json
    - id: check-merge-conflict
    - id: check-yaml
      args: ["--unsafe"]
    - id: trailing-whitespace