# main playbook for the slave nodes
  # name of the playbook
- name: Configure nodes
  # on which hosts to act
  hosts: all
  # it allows ansible to execute as root
  become: yes
  # whether or not to gather info regarding the nodes
  gather_facts: False

  pre_tasks:
      # install python
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      changed_when: False
      # Load env. variables
    - name: Load variables
      include_vars: variables/default_var.yml

  roles:
    # Insall docker
    - docker
    # Install k8s
    - k8s_general
    # Configure k8s on slaves
    - k8s_nodes
    # Deploy app with autoscaling
    - app_deployment_nodes